name: gym_project_app
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  qr_code_scanner: ^1.0.1
  flutter_dotenv: ^5.0.2
  flutter_map: ^7.0.2
  latlong2: ^0.9.0
  geolocator: ^13.0.1
  flutter_secure_storage: ^9.0.0  # Add this line

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - .env
    - lib/images/
